
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.proyecto1.Analizadores.Parser;

/** CUP generated class containing symbol constants. */
public class parserUsuarioSym {
  /* terminals */
  public static final int NUM = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM"
  };
}

