
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.proyecto1.Analizadores.Parser;

/** CUP generated class containing symbol constants. */
public class parserImagenesSym {
  /* terminals */
  public static final int NUM = 2;
  public static final int error = 1;
  public static final int L_C = 5;
  public static final int L_A = 4;
  public static final int EOF = 0;
  public static final int COM = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUM",
  "COM",
  "L_A",
  "L_C"
  };
}

