
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.carlos.proyecto1.Analizadores.Parser;

import com.carlos.proyecto1.Analizadores.Lexer.capasLexer;
import com.carlos.proyecto1.ED.*;
import com.carlos.proyecto1.Exepciones.*;
import com.carlos.proyecto1.Tokens.token;
import com.carlos.proyecto1.Objetos.*;
import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parserCapas extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return parserCapasSym.class;
}

  /** Default constructor. */
  @Deprecated
  public parserCapas() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parserCapas(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parserCapas(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\011\000\002\002\007\000\002\002\004\000\002\002" +
    "\003\000\002\004\011\000\002\004\003\000\002\005\003" +
    "\000\002\005\002\000\002\003\003\000\002\003\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\006\003\005\004\004\001\002\000\004\007" +
    "\010\001\002\000\004\002\uffff\001\002\000\004\002\007" +
    "\001\002\000\004\002\000\001\002\000\006\003\013\004" +
    "\011\001\002\000\004\005\017\001\002\000\004\010\014" +
    "\001\002\000\004\010\ufffd\001\002\000\010\002\ufff9\003" +
    "\005\004\004\001\002\000\004\002\ufffa\001\002\000\004" +
    "\002\001\001\002\000\004\004\020\001\002\000\004\005" +
    "\021\001\002\000\004\011\022\001\002\000\004\006\023" +
    "\001\002\000\010\003\013\004\011\010\ufffb\001\002\000" +
    "\004\010\ufffc\001\002\000\004\010\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\023\000\004\002\005\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\004\011\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\002\014\003\015\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\006\004\023" +
    "\005\024\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parserCapas$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parserCapas$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parserCapas$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



        
    private Pila errores = new Pila();    
    private AVL arbolCapas = new AVL();
    
    public parserCapas(capasLexer lex){
        super(lex);
    }

    public void report_error(String message, Object info){
        System.out.println("reporterror");
    }
    public void report_fatal_error(String message, Object info){
        System.out.println("reportfatal");
    }

    public void syntax_error(Symbol cur_token){
        token tok = ((token)cur_token.value);
        System.out.println("Parametro inesperado ["+tok.getLexeme()+"] Linea: "+tok.getLine()+" Columna: "+tok.getColumn());
        errores.push("Parametro inesperado ["+tok.getLexeme()+"] Linea: "+tok.getLine()+" Columna: "+tok.getColumn());
    }

    protected int error_sync_size() {
        return 1;
    }

    public Pila getErrores(){
        return errores;
    }

    public AVL getArbolCapas() {
        return arbolCapas;
    }



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parserCapas$actions {
  private final parserCapas parser;

  /** Constructor */
  CUP$parserCapas$actions(parserCapas parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parserCapas$do_action_part00000000(
    int                        CUP$parserCapas$act_num,
    java_cup.runtime.lr_parser CUP$parserCapas$parser,
    java.util.Stack            CUP$parserCapas$stack,
    int                        CUP$parserCapas$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parserCapas$result;

      /* select the action based on the action number */
      switch (CUP$parserCapas$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // s ::= NUM L_A cont L_C sp 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-2)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-2)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-2)).value;
		
        if(e2!=null){
            MatrizDispersa tmp = (MatrizDispersa)e2;
            String tag = ((token)e1).getLexeme();
            try {
                Capa nueva = new Capa(tag, tmp);
                arbolCapas.agregar(new NodoArbol(tag,nueva));
                
            } catch (CloneNodeException ex) {
                System.out.println(ex.getMessage()+" ,Linea: "+((token)e1).getLine()+" Columna: "+((token)e1).getColumn());
                errores.push(String.valueOf(ex.getMessage()+" ,Linea: "+((token)e1).getLine()+" Columna: "+((token)e1).getColumn()));
            }
        }else{
            System.out.println("Errores previos en lectura de la matriz: "+((token)e1).getLexeme()+", Corrija e intente de nuevo, Linea: "+((token)e1).getLine()+" ,Columna: "+((token)e1).getColumn());
            errores.push("Errores previos en lectura de la matriz: "+((token)e1).getLexeme()+", Corrija e intente de nuevo, Linea: "+((token)e1).getLine()+" ,Columna: "+((token)e1).getColumn());
        }
    
              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= s EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-1)).value;
		RESULT = start_val;
              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-1)), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parserCapas$parser.done_parsing();
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // s ::= error 
            {
              Object RESULT =null;

              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("s",0, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // cont ::= NUM COM NUM COM COLOR DOT_COM cont2 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-6)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-6)).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-6)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)).right;
		Object e2 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-4)).value;
		int e3left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-2)).left;
		int e3right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-2)).right;
		Object e3 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-2)).value;
		int e4left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()).left;
		int e4right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()).right;
		Object e4 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.peek()).value;
		
            if(e4!=null){
                MatrizDispersa tmp = (MatrizDispersa)e4;
                try {
                    int x = Integer.parseInt(((token)e2).getLexeme());
                    int y = Integer.parseInt(((token)e1).getLexeme());
                    
                    tmp.agregarNodo(x, y, ((token)e3).getLexeme());
                    
                } catch (InvalidIndexException | CloneNodeException | InvalidStructureException ex) {
                    System.out.println(ex.getMessage()+" ,Linea: "+((token)e1).getLine()+" Columna: "+((token)e1).getColumn());
                    errores.push(String.valueOf(ex.getMessage()+" ,Linea: "+((token)e1).getLine()+" Columna: "+((token)e1).getColumn()));
                }
            }
            RESULT = e4;
            
        
              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("cont",2, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.elementAt(CUP$parserCapas$top-6)), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // cont ::= error 
            {
              Object RESULT =null;

              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("cont",2, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // cont2 ::= cont 
            {
              Object RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()).right;
		Object e1 = (Object)((java_cup.runtime.Symbol) CUP$parserCapas$stack.peek()).value;
		
            RESULT = e1;
        
              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("cont2",3, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // cont2 ::= 
            {
              Object RESULT =null;
		
            RESULT = new MatrizDispersa();
        
              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("cont2",3, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sp ::= s 
            {
              Object RESULT =null;

              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("sp",1, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sp ::= 
            {
              Object RESULT =null;

              CUP$parserCapas$result = parser.getSymbolFactory().newSymbol("sp",1, ((java_cup.runtime.Symbol)CUP$parserCapas$stack.peek()), RESULT);
            }
          return CUP$parserCapas$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parserCapas$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parserCapas$do_action(
    int                        CUP$parserCapas$act_num,
    java_cup.runtime.lr_parser CUP$parserCapas$parser,
    java.util.Stack            CUP$parserCapas$stack,
    int                        CUP$parserCapas$top)
    throws java.lang.Exception
    {
              return CUP$parserCapas$do_action_part00000000(
                               CUP$parserCapas$act_num,
                               CUP$parserCapas$parser,
                               CUP$parserCapas$stack,
                               CUP$parserCapas$top);
    }
}

}
