/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.proyecto1.UI;

import com.carlos.proyecto1.ED.Nodo;
import com.carlos.proyecto1.Exepciones.CloneNodeException;
import com.carlos.proyecto1.Objetos.DatosPrograma;
import com.carlos.proyecto1.Objetos.Imagen;
import com.carlos.proyecto1.Objetos.usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class AgregarImagenUsuario extends javax.swing.JInternalFrame {

    private DatosPrograma datosP;
    /**
     * Creates new form AgregarImagenUsuario
     */
    public AgregarImagenUsuario(DatosPrograma datosP) {
        initComponents();
        this.datosP = datosP;
        this.cargarComboUsuarios();
        this.cargarComboImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboUsuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboImagenes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Agregar Imagen Usuario");

        jLabel1.setText("Usuario:");

        jLabel2.setText("Imagen:");

        jButton1.setText("Agregar Imagen");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = this.jComboUsuarios.getItemAt(this.jComboUsuarios.getSelectedIndex());
        String imagen = this.jComboImagenes.getItemAt(this.jComboImagenes.getSelectedIndex());
        this.agregarImagen(user,imagen);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboImagenes;
    private javax.swing.JComboBox<String> jComboUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void cargarComboUsuarios() {
        this.jComboUsuarios.removeAllItems();
        Object[] array = this.datosP.getUsuarios().AVLtoArrayInOrden();
        usuario tmp = null;
        for (Object object : array) {
            tmp = (usuario) object;
            this.jComboUsuarios.addItem(tmp.getUser());
        }
        
        
    }

    private void cargarComboImagenes() {
        this.jComboImagenes.removeAllItems();
        Nodo tmp = this.datosP.getImagenes().getRaiz();
        Imagen tmpImg = null;
        do {     
            tmpImg = (Imagen) tmp.getContenido();
            this.jComboImagenes.addItem(tmpImg.getId());
            tmp = tmp.getSiguiente();
        } while (tmp != this.datosP.getImagenes().getRaiz());
        
    }

    private void agregarImagen(String user, String imagen) {
        usuario us = (usuario) this.datosP.getUsuarios().buscarNodo(user).getContenido();
        Imagen img = (Imagen) this.datosP.getImagenes().buscar(imagen).getContenido();
        
        try {
            us.getImagenes().agregar(new Nodo(imagen, img));
            JOptionPane.showMessageDialog(this, "Se agrego con exito la imagen \""+imagen+"\" al usuario \""+user+"\"");
        } catch (CloneNodeException ex) {
            JOptionPane.showMessageDialog(this, "El usuario \""+user+"\" ya tiene acceso a la imagen \""+imagen+"\"");
        }
        
    }
}
