/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.carlos.proyecto1.UI;

import com.carlos.proyecto1.ED.ListaDobleEnlazada;
import com.carlos.proyecto1.ED.Nodo;
import com.carlos.proyecto1.Exepciones.NotFoundNodeException;
import com.carlos.proyecto1.Objetos.DatosPrograma;
import com.carlos.proyecto1.Objetos.Imagen;
import com.carlos.proyecto1.Objetos.usuario;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author benjamin
 */
public class eliminarImagen extends javax.swing.JInternalFrame {

    private DatosPrograma dataP;
    /**
     * Creates new form eliminarImagen
     */
    public eliminarImagen(DatosPrograma dataP) {
        initComponents();
        this.dataP=dataP;
        this.cargarComboUsuarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboUsuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboImagenes = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        jLabel1.setText("Usuario:");

        jComboUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUsuariosActionPerformed(evt);
            }
        });

        jLabel2.setText("Imagen:");

        jButton1.setText("Eliminar Imagen");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jComboImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String user = this.jComboUsuarios.getItemAt(this.jComboUsuarios.getSelectedIndex());
        String imagen = this.jComboImagenes.getItemAt(this.jComboImagenes.getSelectedIndex());
        this.eliminarImagen(user,imagen);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUsuariosActionPerformed
        String user = this.jComboUsuarios.getItemAt(this.jComboUsuarios.getSelectedIndex());
        this.cargarComboImagenes(user);
    }//GEN-LAST:event_jComboUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboImagenes;
    private javax.swing.JComboBox<String> jComboUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private void eliminarImagen(String user, String imagen) {
        usuario us = (usuario) this.dataP.getUsuarios().buscarNodo(user).getContenido();
        ListaDobleEnlazada lista = us.getImagenes();
        try {
            lista.eliminar(imagen);
            JOptionPane.showMessageDialog(this, "Se elimino con exito la imagen \""+imagen+"\" enlazada al usuario \""+user+"\"");
            this.cargarComboImagenes(user);
            
        } catch (NotFoundNodeException ex) {
            JOptionPane.showMessageDialog(this, "No existe una imagen \""+imagen+"\" enlazada al usuario \""+user+"\"");
        }
    }

    private void cargarComboUsuarios() {
        this.jComboUsuarios.removeAllItems();
        Object[] array = this.dataP.getUsuarios().AVLtoArrayInOrden();
        usuario user = null;
        for (Object object : array) {
            user = (usuario) object;
            this.jComboUsuarios.addItem(user.getUser());
        }
    }
    private void cargarComboImagenes(String user){
        usuario us = (usuario) this.dataP.getUsuarios().buscarNodo(user).getContenido();
        
        ListaDobleEnlazada lista = us.getImagenes();
        this.jComboImagenes.removeAllItems();
        if(lista.isEmpty()){
            JOptionPane.showMessageDialog(this, "El usuario no tiene ninguna Imagen enlazada no puede eliminar nada de este usuario");
            this.jButton1.setEnabled(false);
        }else{
            Nodo nodoTmp = lista.getRaiz();
            Imagen tmpImg = null;
            while (nodoTmp!=null) {
                tmpImg = (Imagen) nodoTmp.getContenido();
                this.jComboImagenes.addItem(tmpImg.getId());
                nodoTmp = nodoTmp.getSiguiente();
            }
            this.jButton1.setEnabled(true);
        }
    }
}
